package master_artigo_nevoa.master;

import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Helbert Monteiro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Master
     */
    ArrayList<Node> listaNodes = new ArrayList<>();

    public Principal() {
        initComponents();
        jpNode.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jbNovoNode = new javax.swing.JButton();
        jbIniciaMaster = new javax.swing.JButton();
        jpNode = new javax.swing.JPanel();
        jlPorta = new javax.swing.JLabel();
        jtfPorta = new javax.swing.JTextField();
        jlIP = new javax.swing.JLabel();
        jtfIP = new javax.swing.JTextField();
        jbCriaNode = new javax.swing.JButton();
        jbCancelaNode = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbNovoNode.setText("Novo Node");
        jbNovoNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoNodeActionPerformed(evt);
            }
        });

        jbIniciaMaster.setText("Iniciar Master");
        jbIniciaMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciaMasterActionPerformed(evt);
            }
        });

        jpNode.setBackground(new java.awt.Color(204, 204, 255));

        jlPorta.setText("Porta:");

        jlIP.setText("IP:");

        jbCriaNode.setText("OK");
        jbCriaNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriaNodeActionPerformed(evt);
            }
        });

        jbCancelaNode.setText("Cancelar");
        jbCancelaNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelaNodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNodeLayout = new javax.swing.GroupLayout(jpNode);
        jpNode.setLayout(jpNodeLayout);
        jpNodeLayout.setHorizontalGroup(
            jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNodeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPorta)
                    .addComponent(jlIP))
                .addGap(18, 18, 18)
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfPorta)
                    .addComponent(jtfIP, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCancelaNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCriaNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jpNodeLayout.setVerticalGroup(
            jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPorta)
                    .addComponent(jtfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCriaNode))
                .addGap(18, 18, 18)
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIP)
                    .addComponent(jtfIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelaNode))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbIniciaMaster)
                    .addComponent(jbNovoNode))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovoNode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jbIniciaMaster)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoNodeActionPerformed
        jbNovoNode.setVisible(false);
        jbIniciaMaster.setVisible(false);
        jpNode.setVisible(true);
    }//GEN-LAST:event_jbNovoNodeActionPerformed

    private void jbCriaNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriaNodeActionPerformed
        Node node = new Node();
        node.setPorta(String.valueOf(jtfPorta.getText()));
        node.setIp(String.valueOf(jtfIP.getText()));
        listaNodes.add(node);
        jtfPorta.setText("");
        jtfIP.setText("");
        jpNode.setVisible(false);
        jbNovoNode.setVisible(true);
        jbIniciaMaster.setVisible(true);
    }//GEN-LAST:event_jbCriaNodeActionPerformed

    private void jbCancelaNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelaNodeActionPerformed
        jtfPorta.setText("");
        jtfIP.setText("");
        jpNode.setVisible(false);
        jbNovoNode.setVisible(true);
        jbIniciaMaster.setVisible(true);
    }//GEN-LAST:event_jbCancelaNodeActionPerformed

    private void jbIniciaMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciaMasterActionPerformed
       // new Conexao(listaNodes);
    }//GEN-LAST:event_jbIniciaMasterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbCancelaNode;
    private javax.swing.JButton jbCriaNode;
    private javax.swing.JButton jbIniciaMaster;
    private javax.swing.JButton jbNovoNode;
    private javax.swing.JLabel jlIP;
    private javax.swing.JLabel jlPorta;
    private javax.swing.JPanel jpNode;
    private javax.swing.JTextField jtfIP;
    private javax.swing.JTextField jtfPorta;
    // End of variables declaration//GEN-END:variables
}
